### ISSUE TITLE
Errors on BODS JSON from register

### ISSUE THREAD

**Issue by mrloop** [openownership/visualisation-tool#142]
Using the [BODS JSON](https://register.openownership.org/entities/17979576658742990570.json) from https://register.openownership.org/entities/17979576658742990570 and the visualizer errors.

![image](https://github.com/openownership/visualisation-tool/assets/12345/eabd57d5-7e2b-4db6-8aa7-da1efa459208)

[17979576658742990570.json](https://github.com/openownership/visualisation-tool/files/13907776/17979576658742990570.json)

**Comment by StephenAbbott** [comment]
@mrloop Hi Ewan. Thanks for raising this - and apologies that we have not fixed this already.

If you look at the following issue - https://github.com/openownership/register/issues/206 - raised on our [main Open Ownership Register repository](https://github.com/openownership/register/), you can see a conversation about why this bug is happening due to our use of the `replacesStatement` field for some [Open Ownership Register data](https://bods-data.openownership.org/source/register) following our [relaunch of the Register last year](https://www.openownership.org/en/news/the-new-open-ownership-register-faster-more-efficient-and-produces-more-detailed-beneficial-ownership-data/).

We are working to prioritise time to look to fix this as soon as we can.

**Comment by kd-ods** [comment]
This issue relates to #141 .

**Comment by codemacabre** [comment]
This now renders, as the following. @kd-ods, is this correct?

![Image](https://github.com/user-attachments/assets/700e6e9f-a922-4def-9d0f-b259af58fcdc)
