### ISSUE TITLE
Validate input to alert the user when we can't parse it as BODS

### ISSUE THREAD

**Issue by stevenday** [openownership/visualisation-tool#18]
Currently, the tool just errors if what you paste isn't a JSON array that looks like BODS statements. Long term, we could look to use https://datareview.openownership.org to properly validate the data, but it would be a useful UX improvement just to catch parsing errors and tell the user something went wrong, rather than silently erroring.

**Comment by kd-ods** [comment]
Things have moved on since this was posted. We now say that:

> The visualiser requires JSON data with a minimum set of data fields to produce a directed graph. It is not necessary for the supplied JSON data to be valid BODS data, but it must meet these minimum requirements.

From: [BODS Visualiser specification](https://github.com/openownership/visualisation-tool/blob/master/docs/spec.md)

I don't think there's much silent erroring, but the error message does need to be improved. (And is there only  one error message??) Currently I got:

> Sorry, there was an error drawing your data. Is it valid BODS?

It would be more helpful to say sthg like: "There was an error drawing your data. Does it conform to the [data requirements](https://github.com/openownership/visualisation-tool/blob/master/docs/spec.md#data-requirements)?"
