### ISSUE TITLE
Write some tests

### ISSUE THREAD

**Issue by stevenday** [openownership/visualisation-tool#27]
In some kind of order of priority:
- A general 'does it work' acceptance test, driving the main library through JSDOM, and/or driving the whole demo app through a headless browser.
- Unit tests for data parsing and sanitising data
- Unit tests for template rendering
- Unit tests for D3 rendering

**Comment by kd-ods** [comment]
Myles, as I started looking at this, it was obvious that we need to work on the Spec in parallel. So I've [started that here](https://docs.google.com/document/d/15YBQbPixnS1i1qe4RlXfkx8wchVsvuEI3ZrCS_pOg5A/edit). I'd like to check my thinking with you today.

**Comment by codemacabre** [comment]
Since the above comment, I've got Jest working together with Puppeteer and I'm struggling to find a decent way to test the SVG output. It's making me sway towards choice 3, as there don't seem to be any standards for testing that the SVGs have rendered correctly.

A couple of options occur to me:
- Checking the SVG for expected text content (Cypress can do this with the `.contains` method)
- Using snapshot testing to perform a visual diff between screenshots of the SVG output (most end-to-end testing frameworks can do this)

But neither of them feel like particularly good means to assert that an SVG has actually rendered correctly and are fairly blunt instruments. I'd probably prefer to focus on writing end-to-end tests to cover more of the logic.

**Comment by codemacabre** [comment]
Thanks @kd-ods. Yes, I did mean unit tests! I appreciate your input; it gives me a good direction forwards.
