### ISSUE TITLE
Add additional edges to show direct/ultimate ownership

### ISSUE THREAD

**Issue by stevenday** [openownership/visualisation-tool#5]
In the following image, the grey dashed line is an example of a concept for distinguishing between direct and indirect ownership:

![image](https://user-images.githubusercontent.com/663700/77956349-a1658780-72c9-11ea-96da-4daceb82a2ff.png)

The grey line shows who the ultimate owner is and is annotated with a calculated percentage showing their eventual share ownership. (For the purposes of this ticket, ignore the other details in the image.) Technically, this would be driven by the `isComponent` and `componentStatementIDs` fields in the data standard.

For the purposes of this experiment, we can assume that calculating the percentage ownership is out of scope. We solely want to understand if it's possible to display these additional edges in a way that is understandable. Especially in a way that works in more complex graphs (i.e. Kwik Fit https://register.openownership.org/entities/59b9197d67e4ebf340d33ddc/graph).

**Comment by kd-ods** [comment]
Just wanted to note that we've got an example now from the [Armenian ZCMC declaration](https://drive.google.com/file/d/11s5zLDbn9ENbaC0o2fMrfEFKsh9dZVPY/view?usp=sharing) where the indirect ooc interests between BOs and the declaring entity are disclosed as are the component intermediaries. This results in lots of solid lines: no differentiation between the actual direct relationships and the 'summary' indirect relationship. It's a good test case.

**Comment by timgdavies** [comment]
@kd-ods I've opened #35 to address the specific issue of showing when `"interestLevel":"indirect"`

**Comment by kd-ods** [comment]
The edge rendering and visualisation of indirect relationships has moved on since this ticket was opened. (For example, relationship edges marked as 'indirect' are now dotted - not solid - lines. And the layout of edges is better.)

>  start with the simple case where the data explicitly declares the relationship and worry about other ways we can infer similar things later.

Development of the BODS visualiser is [focusing](https://github.com/openownership/visualisation-tool/blob/master/docs/spec.md) on explicitly declared information in the data, rather than making and visualising inferences. 

@StephenAbbott  - I suggest we close this ticket as out-of-date. If anyone wants to suggest a new feature relating to inferred relationships, starting a new ticket would be best.
