### ISSUE TITLE
Resolve SVG flags issues

### ISSUE THREAD

**Issue by Lathrisk** [openownership/visualisation-tool#90]
We have moved to importing SVG files and embedding them into the document to enable the pure SVG download. The flag SVG files we were using are inconsistent and some are proportioned differently and are missing the viewBox parameter.

I intended to replace these with a more consistent alternative.

**Comment by Lathrisk** [comment]
@kd-ods @StephenAbbott I have added a new set of flags from [this repo](https://github.com/lipis/flag-icons).

They are far more consistent than the old flag sets. These are either 4x3 or 1x1. I've opted for the 4x3 because they look slightly more natural. There are other options if we want to preserve the original aspect ratio of flags, but a fixed aspect ratio makes the positioning a little easier.

I'm happy to slot in any flag set so long as the SVGs are relatively consistent so if the preference isn't 4x3 I can switch them over.

**Comment by Lathrisk** [comment]
@StephenAbbott I hadn't noticed that, good spot. At present we don't display anything if we don't know the country. My question would be whether this flag adequately communicates that we don't know what the country is.

I wonder if we should create something that follows the existing pattern that we use elsewhere, i.e. a question mark in the middle of a blank flag. This is the pattern we use for all of the unknown node types.

**Comment by StephenAbbott** [comment]
@Lathrisk Realised I responded too fast. @tymonk @kd-ods, Virgil and I have been having a related discussion over email about the new stateBody icon that Virgil is creating. 

We've tried to imagine scenarios where we know which state it is which controls the SOE, but not which body specifically the state controls (due to poor SOE reporting data).

So in line with the [BOVS vocabulary](https://www.openownership.org/visualisation/core/vocabulary/), let's follow the existing pattern for [unknown node types](https://www.openownership.org/visualisation/core/unknowns/) if there are cases where we'd need to show unknown state.
