### ISSUE TITLE
Interest types - owns/controls mapping missing

### ISSUE THREAD

**Issue by Blueskies00** [openownership/visualisation-tool#97]
At least five interest types don’t seem to have a colour mapping to “owns” or “controls”:
other-influence-or-control
appointment-of-board
senior-managing-official
rights-to-surplus-assets-on-dissolution
settlor-of-trust

This is regardless of interest level being direct or indirect.

Data: https://drive.google.com/file/d/1LxkG2qt4icpO7tJ3luvYgo5czGKbLN09/view
![bods(4)](https://user-images.githubusercontent.com/100690440/159490170-267509d4-64a3-4642-8bca-b5ea23e2808d.svg)

**Comment by kd-ods** [comment]
Thanks @Blueskies00. Yes, only a minimal set of information about interests is currently rendered. Addressing this will involve a holistic look at how interests are represented in BODS and working out what information about them can be consistently and usefully represented visually. 

I've spoken to @StephenAbbott about this work and how it's too much to take on for Sprint 4.

Nevertheless, while you've got your head in the code, @Lathrisk, could you add to this issue what the current state of affairs is re rendering interests. For example: which interest types map to ownership or control, and when is the share property picked up as a magnitude of the interest? What happens when an ooc statement contains multiple interests etc? (It's good to stash that info here in case we have time to think about it before the next sprint.)

**Comment by Lathrisk** [comment]
@kd-ods @Blueskies00 

At present the functionality is fairly limited. We only use the `voting-rights` or `shareholding` interest types. We also assume that they are only ever listed once in an interests statement. The current logic generates a new array with a single key for either `voting-rights` or `shareholding`. In effect this means that if, for example, `shareholding` occurs multiple times in the interests array then we overwrite previous values with the following data (it ingests them sequentially).

I think there are a number of options in how we can improve this, and I hope the details above help. Let me know if anything is unclear or needs further discussion.

**Comment by kd-ods** [comment]
@StephenAbbott - we'll need to specify the intended behaviour of the visualiser with regard to the different interest types, their classification as ownership or control, and the use of the `share` property. I'll look at that this week.

(There is a review of [interest modelling in BODS](https://github.com/openownership/data-standard/issues/466) in the feature pipeline. We can note any issues raised by this visualisation work on that ticket if appropriate.)

**Comment by kd-ods** [comment]
Here is a [draft spec of expected behaviour](https://docs.google.com/document/d/1hCjhl7PLQ3bOpeeqO9gis9lDcNbV_HKIpBwPNklK6Cs/edit?usp=sharing). I've needed to review use of dotted lines to represent indirect interests too. @codemacabre - is the way that I've specced this out ok? Is there any other information that you need? Are there any elements of the spec that need to be reconsidered?

NB: The [Visualiser docs](https://github.com/openownership/visualisation-tool/blob/master/docs/spec.md) should be updated as the final stage of this work.

**Comment by codemacabre** [comment]
The new version of the graph @Blueskies00 posted at the start of this issue is now as follows:


![Image](https://github.com/user-attachments/assets/e2f109f6-2876-49d2-955f-558ceb167da9)
